### ISSUE TITLE
Application not responding, what is the entrypoint of the app? 

### ISSUE THREAD

**Issue by saikia1** [mitmedialab/medrec#1] opened 2018-05-08 12:29 UTC
After following the installation instruction for production I'm not able to see results

I have also ran the following commands
`
$ ./medrec EthereumClient 
$ ./medrec DatabaseManager   
$ ./medrec UserClient 
`

**Comment by Firescar96** [comment] 2018-05-08 20:06
What Operating System are you on?

**Comment by Firescar96** [comment] 2018-05-08 20:11
My first response is you should run `go build` before trying to use the medrec binary. But it would help if you could provide any sort of error logs from the terminal.

**Comment by saikia1** [comment] 2018-05-09 05:40
I'm using Ubuntu 16.04. There are no outputs or error messages when I ran the three commands . I also tried running `build-linux-amd64.sh` for build; but still no luck.

**Comment by Firescar96** [comment] 2018-06-28 07:45
I just pushed an update changing a fair amount of how MedRec works and added a release for [amd64 systems](https://github.com/mitmedialab/medrec/releases/tag/untagged-74de072d6fab080ae5a5)

please try again

**Comment by karthyk16** [comment] 2018-07-19 20:09
@Firescar96 : I have taken the latest Master branch and trying to setup a dev environment.. Running in Mac system. I am able to launch the UserClient frontend and able to see the login/register page. But, i try to create a new user or try to login, there is no response and can't see any thing in network as well when i do inspect. Kindly let me know if i am missing something. Should  i try with the above link that you have shared.?

**Comment by Firescar96** [comment] 2018-07-19 20:17
Open inspect and look at the Console tab instead of Network. Post if there are any errors there.
You should be able to create a new user, return to the login page, and then login.

**Comment by Firescar96** [comment] 2018-07-19 20:19
Also, try using the production instructions.

**Comment by Firescar96** [comment] 2018-07-19 21:06
I merged a branch https://github.com/mitmedialab/medrec/pull/2 called "onlyproduction" that I think permanently breaks the use of ganache-cli, and therefore the development instructions. Try following the production instructions.

**Comment by sudhirgiri2911** [comment] 2018-07-20 06:53
@Firescar96 
When i run this command while following production instruction.
1)  ./medrec-amd64 DatabaseManager
2018/07/20 12:14:20 Failed to get the filter logs: Post http://localhost:8545: dial tcp 127.0.0.1:8545: getsockopt: connection refused
2) ./medrec-amd64 UserClient
2018/07/20 12:17:02 User client Exited
2018/07/20 12:17:02 exit status 127
Can you please let me know why I'm getting this. 
Additional infromation about my system:- Ubuntu 17.04

**Comment by Firescar96** [comment] 2018-07-20 08:55
Each command is supposed to be run in a different terminal. The first error suggests `./medrec-amd64 EthereumClient` hasn't run long enough to have finished starting yet.

**Comment by sudhirgiri2911** [comment] 2018-07-20 08:57
Yeah thanks that i figured it out. Can you please tell me about the second one.

**Comment by Firescar96** [comment] 2018-07-20 09:03
Looks like a [command not found error](https://duckduckgo.com/?q=exit+status+127&t=vivaldi&ia=qa), maybe you skipped step 2 of the production instructions. Otherwise I don't know.

**Comment by Firescar96** [comment] 2018-07-21 20:12
This has been helpful for realizing the documentation is now severly out of date, thanks to all of you for making efforts to run this software. I'll try setting up from scratch and maybe I'll run into the same problems.

**Comment by karthyk16** [comment] 2018-07-23 04:54
@Firescar96 : Were you able to run the application.?

**Comment by karthyk16** [comment] 2018-07-23 17:03
@Firescar96 :  I followed the production instruction and did the below.

Run Ethereum client first and waited for it to load.
Run Database MAnager
Run User Client.

UI Opened with landing screen. Tried registering a user, I could see POST /LocalRPC in Database manager log and a KEy prompted in UI. USed the key and created a user. Again i could see POST /LocalRPC and darwmin in the database manager logs. But user didnt get created. Can you tell me if i am missing something.

**Comment by Firescar96** [comment] 2018-07-23 21:14
I just downloaded and installed MedRec. I changed the instructions slightly, there's another component that needs to be installed that was missing before. I would recommend starting over with the production instructions, creating a user, then logging in with your chosen username.

I found and fixed an error with how the EthereumClient is started, but if you haven't logged in yet you wouldn't have encountered it. You'll need to pull the latest commit and delete the folder MedRec created at `${HOME}/.medrec`

**Comment by Firescar96** [comment] 2018-12-04 07:05
I'm leaving this open because the readme could use some work, but I was successful opening the app by following the production instructions

**Comment by swjang** [comment] 2018-12-08 04:35
> What Operating System are you on?

Can I use MacOS?

**Comment by Firescar96** [comment] 2018-12-08 17:11
This application was developed with team members using both debian and macos, I'm sure it works on Ubuntu as well. The errors you posted are not related to medrec. You would be best searching DuckDuckGo or StackOverflow for solutions.

**Comment by swjang** [comment] 2018-12-09 17:21
> This application was developed with team members using both debian and macos, I'm sure it works on Ubuntu as well. The errors you posted are not related to medrec. You would be best searching DuckDuckGo or StackOverflow for solutions.



> I just pushed an update changing a fair amount of how MedRec works and added a release for [amd64 systems](https://github.com/mitmedialab/medrec/releases/tag/untagged-74de072d6fab080ae5a5)
> 
> please try again

In my case, I encountered the following messages.
./medrec-amd64 EthereumClient
-bash: ./medrec-amd64: cannot execute binary file

**Comment by Firescar96** [comment] 2018-12-09 17:35
MacOS is not an amd64 system, it's darwin. You should install golang and run `go build` to build for you operating system.

**Comment by swjang** [comment] 2018-12-09 17:50
> I should have specified the binary is for amd64-linux systems, as that is what I own. You should install golang and run `go build` to build for you operating system.

Would you let me know how to 'go build' in my environments?

**Comment by nikhilvariar** [comment] 2019-03-26 14:32
> > What Operating System are you on?
> 
> Can I use ubuntu 18.04?
> 
> I encountered the following errors.
> ....$ sudo npm install
> npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
> 
> > sha3@1.2.0 install /home/parallels/medrec/UserClient/node_modules/sha3
> > node-gyp rebuild
> 
> gyp ERR! configure error
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/parallels/medrec/UserClient/node_modules/sha3/build'
> gyp ERR! System Linux 4.15.0-34-generic
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/parallels/medrec/UserClient/node_modules/sha3
> gyp ERR! node -v v8.14.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-vis-force@0.3.1 requires a peer of [react@0.14.x](mailto:react@0.14.x) - 15.x but none is installed. You must install peer dependencies yourself.
> npm WARN react-vis-force@0.3.1 requires a peer of [react-dom@0.14.x](mailto:react-dom@0.14.x) - 15.x but none is installed. You must install peer dependencies yourself.
> npm WARN The package case-sensitive-paths-webpack-plugin is included as both a dev and production dependency.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sha3@1.2.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/parallels/.npm/_logs/2018-12-08T14_59_25_697Z-debug.log

Any Solution to this issue ?

**Comment by MTonomy-Nchinda-Nchinda** [comment] 2019-03-26 22:57
This is not a bug related to MedRec, but with your npm setup. You'll have to search elsewhere.

**Comment by nikhilvariar** [comment] 2019-03-27 02:19
> This is not a bug related to MedRec, but with your npm setup. You'll have to search elsewhere.

Thank you for the reply.

`sha3@1.2.0 /home/hpuser/go/src/github.com/mitmedialab/medrec/UserClient/node_modules/sha3
node-gyp rebuild`

Does this mean that its searching for a folder named **sha3** inside **medrec/UserClient/node_modules** ?
If so then I'm not able to find any such folder.Is this an issue with my npm setup ?

**Comment by nikhilvariar** [comment] 2019-03-28 14:44
I tried running 
`./medrec EthereumClient`

and I'm getting the following error

> node[1413]: ../src/node_contextify.cc:633:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
/bin/bash: line 1:  1413 Aborted                 node ./GolangJSHelpers/startGeth.js
node[1412]: ../src/node_contextify.cc:633:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
2019/03/28 20:06:17 Ethereum client Exited
2019/03/28 20:06:17 [/bin/bash -c node ./GolangJSHelpers/startGeth.js || node ./GolangJSHelpers/startGeth.js]

I'm trying to run it on my Raspberry Pi 3B+.Please help me figure where I went wrong

**Comment by Firescar96** [comment] 2019-03-28 17:02
@nikhilvariar I don't own a Raspberry PI and this system is not designed to run on one. The RasPI OS architecture is ARM, so anything compiled for amd64-linux systems won't work.

**Closed by Firescar96** 2019-03-28 17:02 UTC
